### ISSUE TITLE
Error for loading user_emb.pkl

### ISSUE THREAD

**Issue by yi0kevin** [HKUDS/XRec#2]
Great work! But there is an error I encountered when running your code XRec\explainer\main.py, it seems that there is a problem for pickle.load() the file user_emb.pkl. The python version I used is python 3.11.8 and requirements are the same as the listed in requirements.txt.

![微信截图_20240621115504](https://github.com/HKUDS/XRec/assets/142086481/681c6aad-d1bf-4d8f-a77b-7f2e1c7973cf)

**Comment by Martin-qyma** [comment]
Thank you for your interest in XRec! The issue was related to Git LFS, and I have resolved it by replacing LFS-tracked files with actual files. You can now re-download this repo. Thanks for bringing this to my attention.

**Comment by yi0kevin** [comment]
> Thank you for your interest in XRec! The issue was related to Git LFS, and I have resolved it by replacing LFS-tracked files with actual files. You can now re-download this repo. Thanks for bringing this to my attention.

Thanks a lot! It really helps.
