### ISSUE TITLE
数据集预处理

### ISSUE THREAD

**Issue by d8e-lab** [HKUDS/XRec#8]
我尝试用原始的Yelp和Amazon-book数据集上按照你们`process/`的步骤处理数据，但是得到的数据量和你们在论文中所展示的数据集数据量不一致，请问你们有做哪些预处理去筛选吗？
我有尝试对Yelp筛选少于50个词的评论，但是似乎并不成功。
另外请问google map的数据集具体是使用哪一个？
非常感谢！

**Comment by Martin-qyma** [comment]
Thank you for your interest in XRec! In line 99 of `process/interaction.py`, you can see that we randomly select a subset of users to control the size, which can be modified as needed. All interactions after this step are used for training the GNN. Subsequently, we choose only a portion of the interactions to generate explanations, and the filtered data can be found in `data/{amazon/yelp/google}/explanation.json`. Therefore, if you notice that the number of explanations is less than the number of interactions used to train the GNN, this is expected and should not be a concern.

For Yelp, I didn’t fully understand your concern about filtering out 50 words. Our process involves selecting a portion of the interactions and then using `gpt-3.5-turbo` to generate 50-word explanations based on raw reviews, details can be seen in `generation/explanation`. Therefore, you don't have to filter out raw reviews longer than 50 words.

Regarding the Google dataset, it can be accessed here: [Google Local Dataset](https://datarepo.eng.ucsd.edu/mcauley_group/gdrive/googlelocal). For our work, we utilized the data specifically from California. We hope this would help.

**Comment by d8e-lab** [comment]
Thanks for answering
