### ISSUE TITLE
Which year's Amazon-book dataset is being used in your project?

### ISSUE THREAD

**Issue by YangJiLin-xmu** [HKUDS/XRec#9]
Thank you for your impressive work!
Could you kindly inform me about the specific year of the Amazon-book dataset that is being utilized in your project? Additionally, if it's not too much trouble, would it be possible for you to provide the original download link for this dataset?

**Comment by Martin-qyma** [comment]
Thank you for your interest in XRec! The dataset we use is Amazon2018, which can be accessed at the following link: `https://cseweb.ucsd.edu/~jmcauley/datasets/amazon_v2`. We hope this will be helpful for you.

**Comment by YangJiLin-xmu** [comment]
Thanks for your help！

**Comment by d8e-lab** [comment]
It's quite strange that the number of dataset in your work is far more less than that we got from the links above, even we sample the 40% of these dataset. Could you give us more details on the processing data? 
Another question is are the interpretations that you generate from the `interaction.json` file? Also, there are so many of them that training takes a long time......

**Comment by Martin-qyma** [comment]
Thank you for your interest in XRec. When generating data, especially for the `amazon` and `google` datasets, we noticed that the data quality of user reviews is not as good as `yelp`. To address this, we manually filter out interactions with blank reviews. More details can be seen in issue #8.

To generate `interaction.json`, you can follow the code provided in `process/interaction.py`. The file will differ based on how you filter those low-quality reviews, the proportion you choose, and the k-core value you decide to use. The 40% in the file is just an example, and you can manually control it to fit the size you need. I recommend you choose 5-core version and only the book category from the above Amazon website. In recommender systems, we usually keep the number of interactions in the millions and the number of users/items in the order of 10^4, which would be sufficient for research purpose.

As for the training time, more details can be found in issue #6, we hope you find it helpful.

**Comment by Martin-qyma** [comment]
Just a correction: the discussion regarding training time is in issue #7.
